# Server Config
server:
    addr: 'localhost:8080'

# Google Cloud Storage Config
googleAccessKeyID: 'GOOG1EMGUURES77X6DIZEPF45TBM7ZH2ATQKX5PLUWB7FELW4DAN53G25T2II'
googleAccessKeySecret: 'E/X5km0DcDDkab2k9XP1Czno98rPrF/T5LoOrXyM'
gcsRegion: 'us-east1'
gcsEndpoint: 'https://storage.googleapis.com'

# Digital Ocean Config
digitalOceanAccessKeyID: 'DO00MWFZGUJPYJ3G33Z3'
digitalOceanAccessKeySecret: '7rkrkWay4Da+4nUqI9P+6x+9bjrvYiVRb0ZISu9/IZE'
dosRegion: 'us-east-1'
dosEndpoint: 'https://nyc3.digitaloceanspaces.com'

# Amazon S3 Config
amazonAccessKeyID: 'AKIAT3SMMUAFHO5I2W7V'
amazonAccessKeySecret: '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'
s3Region: 'ap-southeast-1'
s3Endpoint: ''

# JWT Secret Key
jwtSecretKey: 'Wt2L9n7WMV6Ssgmp'

# Bucket Name Config
bucketName: 'testing-vdfs'

# Consumer Config
consumer:
    network: 'tcp'
    brokerAddress: 'localhost:9092'
    topic: 'command-log'
    groupID: 'consumer-vfs'
    partition: 0

# Database Config
database:
    user: 'root'
    pass: 'Wt2L9n7WMV6Ssgmp'
    host: 'localhost'
    port: 3306
    name: 'vfsdb'