apiVersion: v1
kind: Service
metadata:
  name: intermediate-service-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    name: intermediate-service